### ISSUE TITLE
release 1.1

### ISSUE THREAD

**Issue by lsmith77** [flack/createphp#74]
https://github.com/flack/createphp/compare/1.0.0...master :)

**Comment by dbu** [comment]
we should make sure to merge #73 before releasing.

maybe we can start with a RC tag, and try to use the orm things in a demo symfony project to see if it really works as expected.

**Comment by hason** [comment]
@dbu ping, #75 was merged.

**Comment by lsmith77** [comment]
release! :)

**Comment by flack** [comment]
the kraken? :-)

**Comment by flack** [comment]
anything we need to adjust still? Release notes, composer branch alias, etc?

**Comment by dbu** [comment]
there is 1.1 in the changelog already, and composer.json already aliases dev-master to 1.1 so i think it looks good for releaseing 1.1.0

if we add new things, we will have to update composer.json to 1.2-dev but i would only do when need arises

**Comment by flack** [comment]
sorry, I was offline a couple of days, but the release is now tagged & ready
